# Generated by Django 3.2.3 on 2021-05-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('regularity', models.CharField(max_length=5)),
                ('complexity', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.character')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.student')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_class', models.CharField(blank=True, max_length=5, null=True)),
                ('error_number', models.CharField(max_length=5)),
                ('error_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('error_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.character')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.student')),
            ],
        ),
    ]
