# Generated by Django 3.1.1 on 2021-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grade', '0002_auto_20210523_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='character',
            field=models.CharField(max_length=5),
        ),
    ]
