# Generated by Django 3.1.1 on 2021-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grade', '0004_auto_20210523_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
